### PR TITLE
Merge rearchitecture to master

### PR DESCRIPTION
**Pull request by darichey**
The rearchitecture has been live (deployed from `dev`) for about a week with no issues. Let's make it official!

### CODE REVIEW

**Comment by ez314** [comment]
I'm not sure if vercel will scream, so lets

1. Disable vercel
2. Merge this PR
3. Switch GH pages branch to main

assuming the switch is seamless, users will not notice anything wrong

Am I missing anything else that needs to happen?

**Comment by darichey** [comment]
I can't think of anything else! I don't have perms to disable vercel so... @NickBurnett ?

**Review by ez314 — APPROVED** [review]
I've disabled the gh actions for vercel, so maybe we're good to merge. Need to remember to fully disable vercel, tho

**Comment by NickBurnett** [comment]
@ez314 You can just disable it since you have bitwarden access.

**Pull request merged**
